config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'

  # http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user
	validates :ticker, presence: true
	validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
    @api = FinnhubRuby::DefaultApi.new
  	if params[:ticker] == ""
  		@nothing = "Hey! You Forgot To Enter A Symbol"
  	elsif params[:ticker]
			@present = @api.company_profile2({symbol: params[:ticker]})
  		@stock = @api.quote(params[:ticker])
  		if !@present.name
  			@error = "Hey! That Stock Symbol Doesn't Exist. Please Try Again."
  		end
  	end
  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_api

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @error = false
    begin
      @ticker_company = @api.company_profile2({symbol:@stock.ticker})
      @ticker = @api.quote(@stock.ticker)
    rescue
      @error = true
    end

  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)
    save_check = (@stock.save) ? true : false
    error = false
    begin
      ticker_company = @api.company_profile2({symbol:@stock.ticker})
    rescue
      error = true
    end
    respond_to do |format|
      if !error and ticker_company.name.present? and save_check
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        @stock.destroy
        flash.now[:error] = "Stock was not created. Check your input!"
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    save_check = (@stock.update(stock_params)) ? true : false
    error = false
    begin
      ticker_company = @api.company_profile2({symbol:@stock.ticker})
    rescue
      error = true
    end

    respond_to do |format|
      if !error and ticker_company.name.present? and save_check
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        flash.now[:error] = "Stock was not updated. Check your input!"
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end
    def set_api
      @api = FinnhubRuby::DefaultApi.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
		<div class="alert alert-warning alert-dismissable" role="alert">
			<button class="close" data-dismiss="alert">
				<small><sup>x</sup></small>
			</button>
			<%= content_tag(:div, msg) %>
		</div>
<% end %>

app/views/home/_footer.html.erb
<br/><br/><br/><br/><br/>

<center>Copyright (c) Ziya Gökalp Avcı</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <%= link_to "Knock Knock Stock", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      	<%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Add Stock", new_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>You can explore the stock quotes with us and make your portfolio tracking easier</p>

app/views/home/index.html.erb
<h1>Welcome to Knock Knock Stock</h1>
<p style="font-size: medium;">You can enter the stock symbol you are curious about. </p>

<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
	<%= submit_tag 'Lookup' %>
<% end %>


<br/>

<% if @stock and !@error %>
	<%= @present.name %><br/>
	$<%= @stock.c %><br/>

<% elsif @nothing %>
	<%= @nothing %>
<% end %>


<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knock Knock Stock</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>

  	<div class="container">
      <%= render 'home/flash' %>

      <br/>
    	<%= yield %>
    </div>

    <%= render 'home/footer' %>
    <br>
  
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-primary" style="background-color: #49b7e3;">
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% begin %>

        <% if stock.user_id == current_user.id %>
          <% @ticker_company = @api.company_profile2({symbol: stock.ticker}) %>
          <% @ticker = @api.quote(stock.ticker) %>
          <% if !@ticker_company.name %>
            <tr>
              <td><%= link_to "Error", stock %></td>
              <td><%= stock.ticker %></td>
              <td>N/A</td>
              <td>N/A</td>
              <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
              <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
            </tr>
          <% else %>
            <tr>
              <td><%= link_to @ticker_company.name, stock %></td>
              <td><%= @ticker_company.ticker %></td>
              <td>$<%= number_with_precision(@ticker.c, :precision => 2, :delimiter => ',') %></td>
              <td>$<%= number_with_precision(@ticker_company.market_capitalization, :precision => 2, :delimiter => ',') %></td>
              <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
              <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
            </tr>
          <% end %>
        <% end %>
      <% rescue %>
        <tr>
          <td><%= link_to "Error", stock %></td>
          <td><%= stock.ticker %></td>
          <td>N/A</td>
          <td>N/A</td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
  <% if @error %>
    You need to upgrade to the premium package.
  <% else %>
    <% if !@ticker_company.name %>
      The ticker: <%= @stock.ticker %><br/> does not exist!
    <% else %>
      <img src="<%= @ticker_company.logo %>"><br/><br/>

      <h2><%= @ticker_company.name %></h2><br/>

      Ticker Symbol: <%= @ticker_company.ticker %><br/>
      
      Company Sector: <%= @ticker_company.finnhub_industry %><br/>
      
      Current Price: $<%= number_with_precision(@ticker.c, :precision => 2, :delimiter => ',') %><br/>

      Previous Close: $<%= number_with_precision(@ticker.pc, :precision => 2, :delimiter => ',') %><br/>

      Percent Change: <%= @ticker.dp %>%<br/>

      Market Cap: $<%= number_with_precision(@ticker_company.market_capitalization, :precision => 2, :delimiter => ',') %><br/>

      <!-- remove sector reference for stock_quote 3.0 gem -->
    <% end %>
  <% end %>
<br/><br/>
<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>